// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestId } from "../RequestId";

export type ControlPendingEntry = { requestId: RequestId, threadId: string | null, method: string, turnId: string | null, callId: string | null, };
