// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ControlShutdownState } from "./ControlShutdownState";
import type { ControlState } from "./ControlState";

export type ControlStatus = { instanceId: string, state: ControlState, shutdown: ControlShutdownState,
/**
 * Fencing never establishes the outcomes of effects dispatched before it.
 */
reconciliationRequired: boolean, };
