// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DynamicToolNamespaceTool } from "./DynamicToolNamespaceTool";

export type DynamicToolNamespaceSpec = {
/**
 * Keep this namespace on the model tool surface, excluding code-mode wrappers.
 */
modelOnly?: boolean, name: string, description: string, tools: Array<DynamicToolNamespaceTool>, };
